#!/usr/bin/env bash
# feature: _shared
# role:    shared
#
# Generates MANIFEST.md by parsing the `feature:` and `role:` headers
# embedded at the top of every file under widgets/, scripts/, styles/.
# Also reports anomalies: orphans (no header), ghosts (header references
# a feature with no other files), and dissonances (filename prefix
# disagrees with the header's feature).
#
# See CONVENTIONS.md for the header format. Run from anywhere.

set -euo pipefail

EWW_DIR="$HOME/.config/eww"
MANIFEST="$EWW_DIR/MANIFEST.md"

cd "$EWW_DIR"

# ── Tempfiles for accumulation ────────────────────────────────────────────────
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
records="$tmp/records"     # tab-separated: <feature> <role> <path>
orphans="$tmp/orphans"
modules_toc="$tmp/modules" # tab-separated: <module-name> <feature> <line> <source>

: > "$records"
: > "$orphans"
: > "$modules_toc"

# ── Parse a single file's header ──────────────────────────────────────────────
# Headers live in the first ~25 lines, prefixed with ; (yuck), // (scss),
# or # (shell/python). We grep loosely so any prefix works.
parse_file() {
    local path="$1"
    local head
    head=$(head -n 25 "$path" 2>/dev/null || true)

    local feature role
    feature=$(printf '%s\n' "$head" | { grep -m1 -E '^[[:space:]]*[#;/]+[[:space:]]*feature:' || true; } \
              | sed -E 's/^[[:space:]]*[#;/]+[[:space:]]*feature:[[:space:]]*//' | tr -d '[:space:]')
    role=$(printf '%s\n' "$head" | { grep -m1 -E '^[[:space:]]*[#;/]+[[:space:]]*role:' || true; } \
              | sed -E 's/^[[:space:]]*[#;/]+[[:space:]]*role:[[:space:]]*//' | tr -d '[:space:]')

    if [[ -z "$feature" ]]; then
        echo "$path" >> "$orphans"
        return
    fi

    printf '%s\t%s\t%s\n' "$feature" "${role:-unknown}" "$path" >> "$records"

    # Containers carry an inline `modules:` block. Capture entries of the form:
    #   ;   - bar-wifi          (feature: wifi)
    # The parser computes the real line number from the source on demand
    # so the TOC stays maintenance-free.
    if [[ "$role" == "container" ]]; then
        local container_head
        # Read more than 25 lines for containers — TOCs can be long.
        container_head=$(head -n 60 "$path" 2>/dev/null || true)
        printf '%s\n' "$container_head" \
          | sed -nE 's/^[[:space:]]*[#;/]+[[:space:]]*-[[:space:]]+([a-zA-Z0-9_-]+)[[:space:]]+\(feature:[[:space:]]*([a-zA-Z0-9_-]+)\).*/\1\t\2/p' \
          | while IFS=$'\t' read -r mod feat; do
                printf '%s\t%s\t%s\n' "$mod" "$feat" "$path" >> "$modules_toc"
            done
    fi
}

# ── Walk the tree ─────────────────────────────────────────────────────────────
while IFS= read -r -d '' f; do
    parse_file "$f"
done < <(find widgets scripts styles -type f \
           \( -name '*.yuck' -o -name '*.scss' -o -name '*.sh' -o -name '*.py' \) \
           -not -path '*/__pycache__/*' \
           -print0 | sort -z)

# ── Emit MANIFEST.md ──────────────────────────────────────────────────────────
{
    echo "# eww feature manifest"
    echo
    echo "_Auto-generated by \`scripts/_manifest.sh\`. Do not edit by hand._"
    echo
    echo "Each section lists every file declaring \`feature: <name>\` in its header,"
    echo "grouped and ordered by role. Container files (today \`bar.yuck\`) cross-reference"
    echo "their inline modules to the corresponding feature."
    echo

    # Unique features in alphabetical order, but with `_shared` last.
    features=$(awk -F'\t' '{print $1}' "$records" | sort -u | grep -v '^_shared$' || true)
    [ -s "$records" ] && grep -q '^_shared	' "$records" && features="$features
_shared"

    while IFS= read -r feat; do
        [ -z "$feat" ] && continue
        echo "## $feat"
        echo
        # Files that declare this feature, sorted by role then path
        { grep -P "^${feat}\t" "$records" || true; } \
          | awk -F'\t' '{printf "%s\t%s\n", $2, $3}' \
          | sort \
          | while IFS=$'\t' read -r role path; do
                printf -- "- \`%s\`  *(%s)*\n" "$path" "$role"
            done

        # Cross-references from container TOCs (line resolved live)
        { grep -P "\t${feat}\t" "$modules_toc" || true; } \
          | while IFS=$'\t' read -r mod _ src; do
                line=$({ grep -nE "^\(defwidget[[:space:]]+${mod}[[:space:]]" "$src" | head -1 | cut -d: -f1; } || true)
                printf -- "- referenced as module \`%s\` in \`%s:%s\`\n" "$mod" "$src" "${line:-?}"
            done

        echo
    done <<< "$features"

    # ── Orphans ───────────────────────────────────────────────────────────────
    if [ -s "$orphans" ]; then
        echo "## ⚠ Orphans (no \`feature:\` header)"
        echo
        sort "$orphans" | while IFS= read -r p; do
            printf -- "- \`%s\`\n" "$p"
        done
        echo
    fi

    # ── Dissonances ───────────────────────────────────────────────────────────
    # File whose basename does NOT start with its declared feature (followed
    # by `-`, `.`, or end of basename). _shared and bar are exempt.
    diss=$(awk -F'\t' '{
        feature = $1
        path = $3
        n = split(path, parts, "/")
        fname = parts[n]
        sub(/\.[^.]+$/, "", fname)
        sub(/^_/, "", fname)
        if (feature == "_shared" || feature == "bar") next
        pattern = "^" feature "($|[-.])"
        if (fname !~ pattern) {
            printf "%s\t%s\n", path, feature
        }
    }' "$records")
    if [ -n "$diss" ]; then
        echo "## ⚠ Naming dissonances (filename does not start with declared feature)"
        echo
        printf '%s\n' "$diss" | while IFS=$'\t' read -r path feat; do
            printf -- "- \`%s\` declares feature \`%s\` but filename does not start with \`%s-\`\n" "$path" "$feat" "$feat"
        done
        echo
    fi

    # ── Summary ───────────────────────────────────────────────────────────────
    total=$(wc -l < "$records" | tr -d ' ')
    norphans=$(wc -l < "$orphans" | tr -d ' ')
    nfeatures=$(awk -F'\t' '{print $1}' "$records" | sort -u | wc -l | tr -d ' ')
    echo "---"
    echo
    echo "**Summary:** $total tagged files across $nfeatures features. $norphans orphans."
} > "$MANIFEST"

echo "Wrote $MANIFEST"
[ -s "$orphans" ] && echo "Note: $(wc -l < "$orphans" | tr -d ' ') orphan(s); see MANIFEST.md."
exit 0
