#!/usr/bin/env bash
# Generate terminal color config files for alacritty, ghostty, and wezterm
# from a foot-theme.ini file (single source of truth).
# Called by theme-selector.sh after updating foot-theme.ini.
#
# OSC live-color updates are handled separately by theme-apply-foot.sh,
# which already writes to all /dev/pts/* devices (including alacritty,
# ghostty, and wezterm PTYs). This script only handles new-instance colors.
#
# Outputs:
#   ~/.config/alacritty/colors.toml  — imported by alacritty.toml
#   ~/.config/ghostty/colors         — included by ghostty config
#   ~/.config/wezterm/colors.lua     — dofile'd by wezterm.lua

set -u

THEME_FILE="${1:-}"
if [[ -z "$THEME_FILE" || ! -f "$THEME_FILE" ]]; then
    echo "Usage: $0 <foot-theme.ini>" >&2
    exit 1
fi

# Extract a color value from the [colors-dark] section (returns bare 6-char hex)
get_color() {
    awk -v key="$1" '
        /^\[colors-dark\]/ { in_s=1; next }
        /^\[/              { in_s=0 }
        in_s && $0 ~ ("^" key "=[0-9a-fA-F]") {
            sub(/^[^=]+=/, "")
            sub(/[[:space:]].*/, "")
            print substr($0, 1, 6)
            exit
        }
    ' "$THEME_FILE"
}

bg=$(get_color background); fg=$(get_color foreground)
r0=$(get_color regular0);   r1=$(get_color regular1)
r2=$(get_color regular2);   r3=$(get_color regular3)
r4=$(get_color regular4);   r5=$(get_color regular5)
r6=$(get_color regular6);   r7=$(get_color regular7)
b0=$(get_color bright0);    b1=$(get_color bright1)
b2=$(get_color bright2);    b3=$(get_color bright3)
b4=$(get_color bright4);    b5=$(get_color bright5)
b6=$(get_color bright6);    b7=$(get_color bright7)

# ── Alacritty ─────────────────────────────────────────────────────────────────
cat > "$HOME/.config/alacritty/colors.toml" <<EOF
# Auto-generated by apply-theme-terminals.sh — do not edit manually.

[colors.primary]
background = "#${bg}"
foreground = "#${fg}"

[colors.normal]
black   = "#${r0}"
red     = "#${r1}"
green   = "#${r2}"
yellow  = "#${r3}"
blue    = "#${r4}"
magenta = "#${r5}"
cyan    = "#${r6}"
white   = "#${r7}"

[colors.bright]
black   = "#${b0}"
red     = "#${b1}"
green   = "#${b2}"
yellow  = "#${b3}"
blue    = "#${b4}"
magenta = "#${b5}"
cyan    = "#${b6}"
white   = "#${b7}"
EOF

# ── Ghostty ───────────────────────────────────────────────────────────────────
cat > "$HOME/.config/ghostty/colors" <<EOF
# Auto-generated by apply-theme-terminals.sh — do not edit manually.
background = ${bg}
foreground = ${fg}
palette = 0=#${r0}
palette = 1=#${r1}
palette = 2=#${r2}
palette = 3=#${r3}
palette = 4=#${r4}
palette = 5=#${r5}
palette = 6=#${r6}
palette = 7=#${r7}
palette = 8=#${b0}
palette = 9=#${b1}
palette = 10=#${b2}
palette = 11=#${b3}
palette = 12=#${b4}
palette = 13=#${b5}
palette = 14=#${b6}
palette = 15=#${b7}
EOF

# ── WezTerm ───────────────────────────────────────────────────────────────────
cat > "$HOME/.config/wezterm/colors.lua" <<EOF
-- Auto-generated by apply-theme-terminals.sh — do not edit manually.
return {
  foreground = "#${fg}",
  background = "#${bg}",
  ansi = {
    "#${r0}",  -- 0 black
    "#${r1}",  -- 1 red
    "#${r2}",  -- 2 green
    "#${r3}",  -- 3 yellow
    "#${r4}",  -- 4 blue
    "#${r5}",  -- 5 magenta
    "#${r6}",  -- 6 cyan
    "#${r7}",  -- 7 white
  },
  brights = {
    "#${b0}",  -- 0 bright black
    "#${b1}",  -- 1 bright red
    "#${b2}",  -- 2 bright green
    "#${b3}",  -- 3 bright yellow
    "#${b4}",  -- 4 bright blue
    "#${b5}",  -- 5 bright magenta
    "#${b6}",  -- 6 bright cyan
    "#${b7}",  -- 7 bright white
  },
}
EOF
