#!/usr/bin/env bash
# ── Palette Theming ───────────────────────────────────────────────────────────
# Role:     Generates ~/.config/wofi/style.css from the active sway theme.
#           Reads ~/.config/sway/definitions.d/theme.conf, resolves
#           $background-color, $text-color, $accent-color, and $selection-color
#           (supports one level of variable indirection), and emits GTK CSS.
#           Called by theme-selector.sh on every theme switch.
# Files:    theme-wofi.sh
#           ~/.config/sway/definitions.d/theme.conf  (active theme symlink, input)
#           ~/.config/wofi/style.css                 (auto-generated CSS, output)
# Programs: grep
# ─────────────────────────────────────────────────────────────────────────────
set -u

CURRENT_THEME_LINK="$HOME/.config/sway/definitions.d/theme.conf"
WOFI_STYLE="$HOME/.config/wofi/style.css"

if [ ! -L "$CURRENT_THEME_LINK" ]; then
    echo "No theme currently set" >&2
    exit 1
fi

theme_path=$(readlink -f "$CURRENT_THEME_LINK")

# Resolve a sway variable to its hex color value (handles one level of indirection)
resolve_var() {
    local path="$1" varname="$2"
    local value
    value=$(grep -oP "set \\\$$varname\s+\K\S+" "$path" | head -1)
    if [[ "$value" == "#"* ]]; then
        echo "$value"
    elif [[ "$value" == '$'* ]]; then
        resolve_var "$path" "${value#$}"
    fi
}

bg=$(resolve_var "$theme_path" "background-color")
fg=$(resolve_var "$theme_path" "text-color")
accent=$(resolve_var "$theme_path" "accent-color")
selection=$(resolve_var "$theme_path" "selection-color")

bg="${bg:-#1c1c1c}"
fg="${fg:-#eeeeee}"
accent="${accent:-#55b5db}"
selection="${selection:-#282828}"

cat > "$WOFI_STYLE" << EOF
/* Auto-generated by theme-wofi.sh — do not edit manually.
 * Source: ~/.config/sway/definitions.d/theme.conf
 * Part of the Palette Theming system — see man palette-theming */

window {
    margin: 0px;
    border: 2px solid ${accent};
    background-color: ${bg};
    border-radius: 5px;
}

#input {
    margin: 5px;
    border: 2px solid ${accent};
    border-radius: 5px;
    background-color: ${selection};
    color: ${fg};
    font-size: 18px;
}

#inner-box {
    margin: 5px;
    border: none;
    background-color: transparent;
}

#outer-box {
    margin: 5px;
    border: none;
    background-color: transparent;
}

#scroll {
    margin: 0px;
    border: none;
}

#text {
    margin: 5px;
    color: ${fg};
    font-size: 16px;
}

#entry {
    padding: 5px;
    border-radius: 5px;
}

#entry:selected {
    background-color: ${selection};
    border-radius: 5px;
}

#entry:selected #text {
    color: ${accent};
    font-weight: bold;
}

#img {
    margin-right: 10px;
}
EOF
