# gruvbox-dark

# some global theme specific variables
set $gtk-theme gruvbox-dark-gtk
set $icon-theme Gruvbox-Plus-Dark
set $cursor-theme Simp1e-Gruvbox-Dark
set $gui-font Roboto 11
set $term-font JetBrainsMono NF
set $gtk-color-scheme prefer-dark
set $kvantum-theme Gruvbox
set $background $HOME/.config/sway/generated_background.svg

set $color0  #1d2021
set $color1  #3c3836
set $color2  #504945
set $color3  #7c6f64
set $color4  #83a598
set $color5  #d5c4a1
set $color6  #ebdbb2
set $color7  #fbf1c7
set $color8  #cc241d
set $color9  #d65d0e
set $color10 #d79921
set $color11 #98971a
set $color12 #fabd2f
set $color13 #83a598
set $color14 #b16286
set $color15 #928374

set $background-color $color0
set $text-color $color6
set $selection-color $color1
set $accent-color $color12

# Property Name         Border   BG       Text    Indicator Child Border
client.focused          $color12 $color12 $color0 $color6   $color12
client.focused_inactive $color1  $color1  $color5 $color3   $color1
client.unfocused        $color1  $color0  $color5 $color6   $color1
client.urgent           $color8  $color8  $color0 $color9   $color8
client.placeholder      $color0  $color0  $color5 $color0   $color0
client.background       $color7
