# tokyo-night

# some global theme specific variables
set $gtk-theme Tokyonight-Dark
set $icon-theme Tokyonight-Dark
set $cursor-theme Simp1e-Tokyo-Night
set $gui-font Roboto 11
set $term-font JetBrainsMono NF
set $gtk-color-scheme prefer-dark
set $kvantum-theme KvAdaptaDark
set $background $HOME/.config/sway/generated_background.svg

set $color0  #1a1b26
set $color1  #292e42
set $color2  #3d59a1
set $color3  #565f89
set $color4  #7aa2f7
set $color5  #a9b1d6
set $color6  #c0caf5
set $color7  #ffffff
set $color8  #f7768e
set $color9  #ff9e64
set $color10 #e0af68
set $color11 #9ece6a
set $color12 #7aa2f7
set $color13 #7dcfff
set $color14 #bb9af7
set $color15 #73daca

set $background-color $color0
set $text-color $color6
set $selection-color $color1
set $accent-color $color12

# Property Name         Border   BG       Text    Indicator Child Border
client.focused          $color12 $color12 $color0 $color6   $color12
client.focused_inactive $color1  $color1  $color5 $color3   $color1
client.unfocused        $color1  $color0  $color5 $color6   $color1
client.urgent           $color8  $color8  $color0 $color9   $color8
client.placeholder      $color0  $color0  $color5 $color0   $color0
client.background       $color7
